// SYNTHETIC FIXTURES ONLY: every DAT, SPR, OTML and OTFI byte in this file is
// generated by the helpers below. Nothing here is PokeAlliance client data and
// these tests never read the owner's local client files.

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

import {
  PNG_SIGNATURE,
  SpriteFile,
  TILE_SIZE,
  ThingsFormatError,
  composeFrame,
  decodePng,
  encodePng,
  encodePngStream,
  indexOtmlSection,
  isFullyTransparent,
  parseDat,
  parseOtfi,
  parseOtml,
  scalePixels,
  spriteIndex,
} from '../../scripts/assets/lib/otclient-things.mjs';
import {
  CLIENT_INSTALL_DIR,
  CliError,
  assertReusableOutputDir,
  assertSafeOutputDir,
  isPathInside,
  normalizeUserPath,
  resolveThingsInputs,
} from '../../scripts/assets/lib/things-cli.mjs';
import {
  formatMappingDiff,
  frameFileName,
  layerSuffix,
  layoutSheet,
  listCells,
  parseDumpArgs,
  planFrames,
  resolveSelection,
  summarizeOutfit,
  updateMappingText,
} from '../../scripts/assets/lib/outfit-dump.mjs';
import { upsertSpriteEntries } from '../../scripts/assets/lib/sprite-registry.mjs';

type SyntheticGroup = {
  type?: number;
  width: number;
  height: number;
  realSize?: number;
  layers?: number;
  px?: number;
  py?: number;
  pz?: number;
  phases?: number;
  sprites: number[];
  animation?: { async: boolean; loop: number; start: number; durations: [number, number][] };
};

type SyntheticFormat = { extended: boolean; frameGroups: boolean; frameDurations: boolean };

const plainFormat: SyntheticFormat = { extended: true, frameGroups: false, frameDurations: false };

function le16(value: number) {
  return [value & 0xff, (value >> 8) & 0xff];
}

function le32(value: number) {
  return [value & 0xff, (value >>> 8) & 0xff, (value >>> 16) & 0xff, (value >>> 24) & 0xff];
}

/** Synthetic ThingType bytes: attributes, 0xFF terminator, frame group(s), sprite IDs. */
function syntheticThing(attributes: number[], groups: SyntheticGroup[], format = plainFormat) {
  const bytes: number[] = [...attributes, 0xff];
  if (format.frameGroups) bytes.push(groups.length);
  for (const group of groups) {
    if (format.frameGroups) bytes.push(group.type ?? 0);
    bytes.push(group.width, group.height);
    if (group.width > 1 || group.height > 1)
      bytes.push(group.realSize ?? Math.max(group.width, group.height) * TILE_SIZE);
    const phases = group.phases ?? 1;
    bytes.push(group.layers ?? 1, group.px ?? 1, group.py ?? 1, group.pz ?? 1, phases);
    if (format.frameDurations && phases > 1 && group.animation) {
      bytes.push(
        group.animation.async ? 0 : 1,
        ...le32(group.animation.loop),
        group.animation.start & 0xff,
      );
      for (const [min, max] of group.animation.durations) bytes.push(...le32(min), ...le32(max));
    }
    for (const sprite of group.sprites)
      bytes.push(...(format.extended ? le32(sprite) : le16(sprite)));
  }
  return Buffer.from(bytes);
}

/** Synthetic DAT: u32 signature, u16 counts (items start at 100), then things in order. */
function syntheticDat(categories: {
  items?: Buffer[];
  outfits?: Buffer[];
  effects?: Buffer[];
  missiles?: Buffer[];
}) {
  const { items = [], outfits = [], effects = [], missiles = [] } = categories;
  const header = Buffer.from([
    ...le32(0x5eed1234),
    ...le16(99 + items.length),
    ...le16(outfits.length),
    ...le16(effects.length),
    ...le16(missiles.length),
  ]);
  return Buffer.concat([header, ...items, ...outfits, ...effects, ...missiles]);
}

/** Solid 32x32 RGBA tile. */
function solidTile(red: number, green: number, blue: number, alpha = 255) {
  const pixels = Buffer.alloc(TILE_SIZE * TILE_SIZE * 4);
  for (let index = 0; index < TILE_SIZE * TILE_SIZE; index++)
    pixels.set([red, green, blue, alpha], index * 4);
  return pixels;
}

/** OTClient-style run-length sprite encoding (transparent run, colored run, pixels). */
function encodeSprite(pixels: Buffer, transparency: boolean) {
  const chunks: Buffer[] = [];
  let index = 0;
  const total = TILE_SIZE * TILE_SIZE;
  while (index < total) {
    let transparent = 0;
    while (index + transparent < total && pixels[(index + transparent) * 4 + 3] === 0)
      transparent++;
    let colored = 0;
    while (
      index + transparent + colored < total &&
      pixels[(index + transparent + colored) * 4 + 3] !== 0
    )
      colored++;
    if (!colored) break;
    chunks.push(Buffer.from([...le16(transparent), ...le16(colored)]));
    for (let pixel = 0; pixel < colored; pixel++) {
      const offset = (index + transparent + pixel) * 4;
      chunks.push(pixels.subarray(offset, offset + (transparency ? 4 : 3)));
    }
    index += transparent + colored;
  }
  return Buffer.concat(chunks);
}

/** Synthetic extended SPR: u32 signature, u32 count, address table, sprite blocks (null = address 0). */
function syntheticSpr(sprites: (Buffer | null)[], transparency = true) {
  const header = Buffer.alloc(8 + sprites.length * 4);
  header.writeUInt32LE(0x0badf00d, 0);
  header.writeUInt32LE(sprites.length, 4);
  const blocks: Buffer[] = [];
  let offset = header.length;
  sprites.forEach((sprite, index) => {
    if (!sprite) return;
    const data = encodeSprite(sprite, transparency);
    const block = Buffer.concat([Buffer.from([0xff, 0x00, 0xff, ...le16(data.length)]), data]);
    header.writeUInt32LE(offset, 8 + index * 4);
    blocks.push(block);
    offset += block.length;
  });
  return Buffer.concat([header, ...blocks]);
}

function pixelAt(pixels: Buffer, width: number, x: number, y: number) {
  const offset = (y * width + x) * 4;
  return [...pixels.subarray(offset, offset + 4)];
}

const scratch = mkdtempSync(path.join(tmpdir(), 'synthetic-things-'));
let folderCounter = 0;
function syntheticFolder(files: Record<string, Buffer | string>) {
  const folder = path.join(scratch, `case-${folderCounter++}`);
  mkdirSync(folder, { recursive: true });
  for (const [name, content] of Object.entries(files))
    writeFileSync(path.join(folder, name), content);
  return folder;
}

afterAll(() => {
  rmSync(scratch, { recursive: true, force: true });
});

// Synthetic outfit 1: 2x2 tiles, 2 layers, 4 directions, 2 phases, PokeAlliance
// raw-39 extension and a displacement attribute.
const outfitSprites = Array.from({ length: 2 * 2 * 2 * 4 * 2 }, (_, index) => index + 1);
const syntheticOutfit = syntheticThing(
  [
    25,
    ...le16(-6 & 0xffff),
    ...le16(-3 & 0xffff),
    39,
    ...[-12, -6, -9, 0, -11, 0, -13, 0].flatMap((value) => le16(value & 0xffff)),
  ],
  [{ width: 2, height: 2, realSize: 56, layers: 2, px: 4, phases: 2, sprites: outfitSprites }],
);
const emptyOutfit = syntheticThing([], [{ width: 1, height: 1, px: 4, sprites: [0, 0, 0, 0] }]);
const marketItem = syntheticThing(
  [
    22,
    ...le16(3),
    ...le16(193),
    34,
    ...le16(1),
    ...le16(2),
    ...le16(3),
    ...le16(4),
    ...Buffer.from('Test'),
    ...le16(0),
    ...le16(8),
  ],
  [{ width: 1, height: 1, sprites: [1] }],
);
const syntheticDatBuffer = syntheticDat({
  items: [marketItem],
  outfits: [syntheticOutfit, emptyOutfit],
});

describe('DAT reader (synthetic fixtures)', () => {
  it('parses header, attributes (incl. the PokeAlliance extension) and dimensions', () => {
    const dat = parseDat(syntheticDatBuffer, { keep: ['items', 'outfits'] });
    expect(dat.signature).toBe(0x5eed1234);
    expect(dat.counts).toEqual({ items: 100, outfits: 2, effects: 0, missiles: 0 });
    expect(dat.trailingBytes).toBe(0);

    const outfit = dat.things.outfits.get(1)!;
    expect(outfit.attributes.map((attribute) => attribute.name)).toEqual([
      'displacement',
      'pokeAllianceDirectionalOffsets',
    ]);
    expect(outfit.attributes[0].value).toEqual({ x: -6, y: -3 });
    expect(outfit.attributes[1].otclientAttr).toBe(38);
    expect(outfit.attributes[1].payloadHex).toBe('f4fffafff7ff0000f5ff0000f3ff0000');
    expect((outfit.attributes[1].value as { north: unknown }).north).toEqual({ x: -12, y: -6 });

    const [group] = outfit.frameGroups;
    expect(group).toMatchObject({
      name: 'default',
      type: null,
      width: 2,
      height: 2,
      realSize: 56,
      exactSize: 56,
      layers: 2,
      patternX: 4,
      patternY: 1,
      patternZ: 1,
      phases: 2,
      spriteCount: 64,
    });
    expect(group.spriteIds).toEqual(outfitSprites);

    const item = dat.things.items.get(100)!;
    expect(item.attributes[0].value).toEqual({ intensity: 3, color: 193 });
    expect(item.attributes[1].value).toEqual({
      category: 1,
      tradeAs: 2,
      showAs: 3,
      name: 'Test',
      restrictVocation: 0,
      requiredLevel: 8,
    });
  });

  it('keeps only the requested categories', () => {
    const dat = parseDat(syntheticDatBuffer);
    expect(Object.keys(dat.things)).toEqual(['outfits']);
  });

  it('reads frame groups and enhanced animation data when the format enables them', () => {
    const format = { extended: false, frameGroups: true, frameDurations: true };
    const outfit = syntheticThing(
      [],
      [
        { type: 0, width: 1, height: 1, px: 4, phases: 1, sprites: [1, 2, 3, 4] },
        {
          type: 1,
          width: 1,
          height: 1,
          px: 4,
          phases: 2,
          animation: {
            async: true,
            loop: -1,
            start: 0,
            durations: [
              [100, 150],
              [200, 250],
            ],
          },
          sprites: [5, 6, 7, 8, 9, 10, 11, 12],
        },
      ],
      format,
    );
    const dat = parseDat(syntheticDat({ outfits: [outfit] }), {
      format: { ...format, transparency: true },
    });
    const groups = dat.things.outfits.get(1)!.frameGroups;
    expect(groups.map((group) => group.name)).toEqual(['idle', 'moving']);
    expect(groups[0].animation).toBeNull();
    expect(groups[1].animation).toEqual({
      async: true,
      loopCount: -1,
      startPhase: 0,
      durations: [
        { min: 100, max: 150 },
        { min: 200, max: 250 },
      ],
    });
    expect(groups[1].spriteIds).toEqual([5, 6, 7, 8, 9, 10, 11, 12]);
    expect(
      planFrames(dat.things.outfits.get(1)!, 'idle').map((frame) => frameFileName(frame)),
    ).toEqual([
      'idle_north_a0_m0_p0.png',
      'idle_east_a0_m0_p0.png',
      'idle_south_a0_m0_p0.png',
      'idle_west_a0_m0_p0.png',
    ]);
  });

  it('refuses protected PKA1 input and reports truncation', () => {
    const protectedBuffer = Buffer.concat([Buffer.from('PKA1'), Buffer.alloc(32)]);
    expect(() => parseDat(protectedBuffer)).toThrow(/PKA1/);
    expect(() => parseDat(syntheticDatBuffer.subarray(0, syntheticDatBuffer.length - 3))).toThrow(
      ThingsFormatError,
    );
  });
});

describe('frame compositing and SPR reading (synthetic fixtures)', () => {
  it('follows OTClient sprite index order and bottom-right tile anchoring', () => {
    const outfit = parseDat(syntheticDatBuffer).things.outfits.get(1)!;
    const [group] = outfit.frameGroups;
    const expected = spriteIndex(group, { tileX: 1, tileY: 0, layer: 1, x: 2, phase: 1 });
    expect(expected).toBe((((1 * 4 + 2) * 2 + 1) * 2 + 0) * 2 + 1);

    const colours: Record<number, Buffer> = {};
    const readSprite = (id: number) => (colours[id] ??= solidTile(id, 0, 0));
    const frame = composeFrame(group, { x: 2, phase: 1 }, readSprite);
    expect(frame.width).toBe(64);
    expect(frame.spriteIds).toEqual(
      [0, 1, 2, 3].map(
        (tile) =>
          group.spriteIds[
            spriteIndex(group, { tileX: tile % 2, tileY: Math.floor(tile / 2), x: 2, phase: 1 })
          ],
      ),
    );
    // Tile (0,0) lands bottom-right, tile (1,1) top-left.
    expect(pixelAt(frame.pixels, 64, 40, 40)[0]).toBe(frame.spriteIds[0]);
    expect(pixelAt(frame.pixels, 64, 5, 5)[0]).toBe(frame.spriteIds[3]);
  });

  it('reads RGBA and RGB sprites through a file descriptor', () => {
    const red = solidTile(255, 0, 0);
    const corner = Buffer.alloc(TILE_SIZE * TILE_SIZE * 4);
    corner.set([0, 0, 255, 255], (TILE_SIZE * TILE_SIZE - 1) * 4);
    const folder = syntheticFolder({
      'rgba.spr': syntheticSpr([red, null, corner]),
      'rgb.spr': syntheticSpr([red], false),
    });

    const rgba = SpriteFile.open(path.join(folder, 'rgba.spr'));
    try {
      expect(rgba.count).toBe(3);
      expect(rgba.signature).toBe(0x0badf00d);
      expect(rgba.readSprite(1).equals(red)).toBe(true);
      expect(isFullyTransparent(rgba.readSprite(0))).toBe(true);
      expect(isFullyTransparent(rgba.readSprite(2))).toBe(true);
      expect(rgba.readSprite(3).equals(corner)).toBe(true);
      expect(() => rgba.readSprite(4)).toThrow(ThingsFormatError);
    } finally {
      rgba.close();
    }

    const rgb = SpriteFile.open(path.join(folder, 'rgb.spr'), { transparency: false });
    try {
      expect(rgb.readSprite(1).equals(red)).toBe(true);
    } finally {
      rgb.close();
    }
  });

  it('refuses a PKA1 sprite file', () => {
    const folder = syntheticFolder({
      'things.spr': Buffer.concat([Buffer.from('PKA1'), Buffer.alloc(16)]),
    });
    expect(() => SpriteFile.open(path.join(folder, 'things.spr'))).toThrow(/PKA1/);
  });
});

describe('PNG encoder', () => {
  it('writes a valid RGBA PNG that decodes back to the same pixels', () => {
    const pixels = Buffer.alloc(3 * 2 * 4);
    pixels.set([255, 0, 0, 255, 0, 255, 0, 128], 0);
    pixels.set([0, 0, 255, 255], 5 * 4);
    const png = encodePng(pixels, 3, 2);
    expect(png.subarray(0, 8).equals(PNG_SIGNATURE)).toBe(true);
    expect(png.toString('latin1', 12, 16)).toBe('IHDR');
    expect(png.readUInt32BE(16)).toBe(3);
    expect(png.readUInt32BE(20)).toBe(2);
    expect([png[24], png[25]]).toEqual([8, 6]);
    const decoded = decodePng(png);
    expect(decoded.width).toBe(3);
    expect(decoded.height).toBe(2);
    expect(decoded.pixels.equals(pixels)).toBe(true);
    expect(() => encodePng(pixels, 4, 2)).toThrow(RangeError);
  });

  it('scales with nearest neighbour', () => {
    const pixels = Buffer.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const scaled = scalePixels(pixels, 2, 1, 2);
    expect([...scaled]).toEqual([
      ...[1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8],
      ...[1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8],
    ]);
  });

  it('streams large (scaled) PNGs that decode to the same pixels as the in-memory path', async () => {
    const pixels = Buffer.alloc(3 * 2 * 4);
    for (let index = 0; index < pixels.length; index++) pixels[index] = (index * 37) & 0xff;
    for (const scale of [1, 3]) {
      const png = await encodePngStream(pixels, 3, 2, { scale });
      expect(png.subarray(0, 8).equals(PNG_SIGNATURE)).toBe(true);
      const decoded = decodePng(png);
      const expected = decodePng(encodePng(scalePixels(pixels, 3, 2, scale), 3 * scale, 2 * scale));
      expect([decoded.width, decoded.height]).toEqual([3 * scale, 2 * scale]);
      expect(decoded.pixels.equals(expected.pixels)).toBe(true);
    }
    await expect(encodePngStream(pixels, 4, 2)).rejects.toThrow(RangeError);
  });
});

describe('frame naming and sprite-sheet layout', () => {
  it('names frames <group>_<direction>_a<addon>_m<mount>_p<phase>', () => {
    expect(frameFileName({ group: 'default', x: 2, y: 0, z: 0, phase: 0 })).toBe(
      'default_south_a0_m0_p0.png',
    );
    expect(frameFileName({ group: 'moving', x: 3, y: 2, z: 1, phase: 4 }, layerSuffix(1))).toBe(
      'moving_west_a2_m1_p4_mask.png',
    );
    expect(frameFileName({ group: 'default', x: 5, y: 0, z: 0, phase: 0 }, layerSuffix(3))).toBe(
      'default_x5_a0_m0_p0_layer3.png',
    );
  });

  it('plans every group x mount x addon x direction x phase, or phase 0 for idle', () => {
    const outfit = parseDat(syntheticDatBuffer).things.outfits.get(1)!;
    expect(planFrames(outfit, 'all')).toHaveLength(4 * 2);
    expect(planFrames(outfit, 'idle').map((frame) => frame.phase)).toEqual([0, 0, 0, 0]);
  });

  it('names single-direction outfits "any" instead of a facing', () => {
    const oneDirection = syntheticThing([], [{ width: 1, height: 1, phases: 2, sprites: [1, 2] }]);
    const outfit = parseDat(syntheticDat({ outfits: [oneDirection] })).things.outfits.get(1)!;
    expect(planFrames(outfit, 'all').map((frame) => frameFileName(frame))).toEqual([
      'default_any_a0_m0_p0.png',
      'default_any_a0_m0_p1.png',
    ]);
    const layout = layoutSheet(
      planFrames(outfit, 'all').map((frame) => ({ ...frame, width: 32, height: 32 })),
    );
    expect(layout.rows.map((row) => row.key)).toEqual(['default_any_a0_m0']);
  });

  it('lays out rows by direction/addon and columns by phase, anchored bottom-right', () => {
    const frames = [
      { group: 'idle', x: 0, y: 0, z: 0, phase: 0, width: 32, height: 32 },
      { group: 'moving', x: 0, y: 0, z: 0, phase: 0, width: 64, height: 64 },
      { group: 'moving', x: 0, y: 0, z: 0, phase: 1, width: 64, height: 64 },
      { group: 'moving', x: 1, y: 1, z: 0, phase: 1, width: 64, height: 64 },
    ];
    const layout = layoutSheet(frames);
    expect(layout).toMatchObject({
      width: 128,
      height: 192,
      cellWidth: 64,
      cellHeight: 64,
      columns: 2,
    });
    expect(layout.rows.map((row) => row.key)).toEqual([
      'idle_north_a0_m0',
      'moving_north_a0_m0',
      'moving_east_a1_m0',
    ]);
    expect(layout.rects[0]).toEqual({ row: 0, column: 0, x: 32, y: 32, w: 32, h: 32 });
    expect(layout.rects[3]).toEqual({ row: 2, column: 1, x: 64, y: 128, w: 64, h: 64 });
  });
});

describe('dump CLI arguments and selection', () => {
  const mapping = { bulbasaur: 2, charizard: 7, 'shiny-charizard': 509 };

  it('parses selections, repeatable lists and output options', () => {
    const options = parseDumpArgs([
      '--',
      '--id',
      '7,509',
      '--id=12',
      '--range',
      '1-3',
      '--slug',
      'charizard',
      '--frames',
      'idle',
      '--scale',
      '2',
      '--sheet',
      '--layers',
      '--things',
      'C:/synthetic folder/things',
    ]);
    expect(options).toMatchObject({
      ids: [7, 509, 12],
      ranges: [{ from: 1, to: 3 }],
      slugs: ['charizard'],
      frames: 'idle',
      scale: 2,
      sheet: true,
      layers: true,
      things: 'C:/synthetic folder/things',
      hasSelection: true,
    });
    expect(parseDumpArgs(['--map', 'pikachu=25,raichu=26', '--map', 'mew=151']).map).toEqual([
      { slug: 'pikachu', id: 25 },
      { slug: 'raichu', id: 26 },
      { slug: 'mew', id: 151 },
    ]);
    expect(parseDumpArgs(['--list', '--json']).list).toBe(true);
  });

  it('accepts space-separated lists (PowerShell arrays forwarded by the pnpm shim)', () => {
    const options = parseDumpArgs([
      '--id',
      '153 3359',
      '--range',
      '1-3 8-9',
      '--slug',
      'charizard shiny-charizard',
      '--map',
      'pikachu=25 raichu=26',
    ]);
    expect(options.ids).toEqual([153, 3359]);
    expect(options.ranges).toEqual([
      { from: 1, to: 3 },
      { from: 8, to: 9 },
    ]);
    expect(options.slugs).toEqual(['charizard', 'shiny-charizard']);
    expect(options.map.map((entry) => entry.slug)).toEqual(['pikachu', 'raichu']);
  });

  it('rejects missing selections and invalid values with Spanish messages', () => {
    expect(() => parseDumpArgs([])).toThrow(/Indica qué outfits volcar/);
    try {
      parseDumpArgs(['--sheet']);
    } catch (error) {
      expect(error).toBeInstanceOf(CliError);
      expect((error as CliError).showHelp).toBe(true);
    }
    expect(() => parseDumpArgs(['--all', '--scale', '9'])).toThrow(/--scale/);
    expect(() => parseDumpArgs(['--range', '5-1'])).toThrow(/inicio es mayor/);
    expect(() => parseDumpArgs(['--all', '--frames', 'walk'])).toThrow(/--frames/);
    expect(() => parseDumpArgs(['--all', '--bogus'])).toThrow(/Opción desconocida/);
    expect(() => parseDumpArgs(['--all', '--json'])).toThrow(/--list/);
    expect(() => parseDumpArgs(['--map', 'Bad_Slug=3'])).toThrow(/kebab-case/);
    expect(() => parseDumpArgs(['--map', '25=25'])).toThrow(/solo números/);
    expect(() => parseDumpArgs(['--id', '0'])).toThrow(/--id/);
    expect(() => parseDumpArgs(['--out'])).toThrow(/Falta el valor/);
  });

  it('rejects empty option values instead of falling back to defaults', () => {
    expect(() => parseDumpArgs(['--all', '--out', ''])).toThrow(/--out tiene un valor vacío/);
    expect(() => parseDumpArgs(['--all', '--out='])).toThrow(/--out tiene un valor vacío/);
    expect(() => parseDumpArgs(['--list', '--things', '  '])).toThrow(/--things/);
    expect(() => parseDumpArgs(['--list', '--dat', '""'])).toThrow(/--dat/);
    expect(() => normalizeUserPath('""')).toThrow(/ruta vacía/);
  });

  it('resolves ids, ranges, slugs and mapped outfits to a sorted unique list', () => {
    const selection = resolveSelection(
      {
        all: false,
        mapped: false,
        ids: [9, 2],
        ranges: [{ from: 1, to: 3 }],
        slugs: ['charizard'],
      },
      { mapping, outfitCount: 600 },
    );
    expect(selection).toEqual({ ids: [1, 2, 3, 7, 9], warnings: [] });
    expect(
      resolveSelection(
        { all: false, mapped: true, ids: [], ranges: [], slugs: [] },
        { mapping, outfitCount: 600 },
      ).ids,
    ).toEqual([2, 7, 509]);
    expect(
      resolveSelection(
        { all: true, mapped: false, ids: [], ranges: [], slugs: [] },
        { mapping, outfitCount: 4 },
      ).ids,
    ).toEqual([1, 2, 3, 4]);
  });

  it('explains unknown slugs and out-of-range ids', () => {
    const base = {
      all: false,
      mapped: false,
      ids: [] as number[],
      ranges: [] as { from: number; to: number }[],
    };
    expect(() =>
      resolveSelection({ ...base, slugs: ['pikachu'] }, { mapping, outfitCount: 600 }),
    ).toThrow(/Slug desconocido: pikachu[\s\S]*bulbasaur, charizard, shiny-charizard/);
    expect(() =>
      resolveSelection({ ...base, ids: [700], slugs: [] }, { mapping, outfitCount: 600 }),
    ).toThrow(/no existe en el DAT/);
    const clamped = resolveSelection(
      { ...base, ranges: [{ from: 598, to: 900 }], slugs: [] },
      { mapping, outfitCount: 600 },
    );
    expect(clamped.ids).toEqual([598, 599, 600]);
    expect(clamped.warnings[0]).toMatch(/se recortó/);
  });

  it('updates content/outfits.json preserving format, addons and never removing records', () => {
    const addon = {
      id: 'bulbasaur-addon-1',
      nombre: 'Addon',
      outfitId: 1005,
      sprite: 'outfits/1005',
    };
    const text = `${JSON.stringify(
      {
        $schema: './schemas/outfits.schema.json',
        outfits: [
          { pokemon: 'bulbasaur', outfitId: 2, addons: [addon] },
          { pokemon: 'charizard', outfitId: 7, addons: [] },
        ],
      },
      null,
      4,
    ).replace(/\n/g, '\r\n')}\r\n`;
    const update = updateMappingText(text, [
      { slug: 'charizard', id: 8 },
      { slug: 'pikachu', id: 25 },
    ]);
    expect(update.text).toContain('\r\n    "outfits": [\r\n');
    expect(update.text.endsWith('}\r\n')).toBe(true);
    expect(JSON.parse(update.text)).toEqual({
      $schema: './schemas/outfits.schema.json',
      outfits: [
        { pokemon: 'bulbasaur', outfitId: 2, addons: [addon] },
        { pokemon: 'charizard', outfitId: 8, addons: [] },
        { pokemon: 'pikachu', outfitId: 25, addons: [] },
      ],
    });
    expect(update.mapping).toEqual({ bulbasaur: 2, charizard: 8, pikachu: 25 });
    expect(formatMappingDiff(update.changes)).toEqual([
      '- "charizard": 7',
      '+ "charizard": 8',
      '+ "pikachu": 25',
    ]);
    const unchanged = updateMappingText(text, [{ slug: 'bulbasaur', id: 2 }]);
    expect(unchanged.text).toBe(text);
    expect(unchanged.changes).toEqual([]);
    expect(() => updateMappingText('{"bulbasaur": 2}', [])).toThrow(/lista "outfits"/);
  });

  it('accepts --registrar only with an explicit selection', () => {
    expect(parseDumpArgs(['--id', '7', '--registrar']).registrar).toBe(true);
    expect(parseDumpArgs(['--preview'])).toMatchObject({
      mapped: true,
      registrar: true,
      hasSelection: true,
    });
    expect(() => parseDumpArgs(['--all', '--registrar'])).toThrow(/no acepta --all/);
    expect(() => parseDumpArgs(['--list', '--registrar'])).toThrow(/--list/);
    expect(() => parseDumpArgs(['--map', 'mew=151', '--registrar'])).toThrow(
      /--registrar necesita outfits/,
    );
  });

  it('adds or replaces sprite registry entries keeping the rest of the file', () => {
    const text =
      '{\n  "$schema": "../../content/schemas/sprites.schema.json",\n  "sprites": {\n' +
      '    "ui/diamond": {\n      "archivo": "ui/diamond.png",\n      "frame": [32, 32],\n' +
      '      "frames": 7,\n      "modo": "animacion",\n' +
      '      "duracionMs": [110, 110, 110, 110, 110, 110, 110]\n    }\n  }\n}\n';
    const entry = { archivo: 'outfits/7/sur.png', frame: [64, 64], frames: 1, modo: 'estatico' };
    const update = upsertSpriteEntries(text, { 'outfits/7': entry }, 'unused');
    expect(update.changes).toEqual([{ key: 'outfits/7', added: true }]);
    expect(update.text.startsWith(text.slice(0, text.indexOf('    }\n  }')))).toBe(true);
    expect(update.text).toContain('"frame": [64, 64]');
    expect(Object.keys(JSON.parse(update.text).sprites)).toEqual(['ui/diamond', 'outfits/7']);
    const again = upsertSpriteEntries(update.text, { 'outfits/7': entry }, 'unused');
    expect(again.changes).toEqual([]);
    expect(again.text).toBe(update.text);
  });
});

describe('input resolution and output guard (synthetic folders)', () => {
  const dat = syntheticDatBuffer;
  const spr = syntheticSpr([solidTile(1, 2, 3)]);

  it('prefers things_objectbuilder.dat, then things.dat, and detects side files', () => {
    const folder = syntheticFolder({
      'things_objectbuilder.dat': dat,
      'things.dat': dat,
      'things.spr': spr,
      'things.otml': 'creatures:\n  7\n    opacity: 0.7\n',
      'things.otfi': 'DatSpr\n  extended: true\n',
    });
    const inputs = resolveThingsInputs({ things: folder }, { env: {} });
    expect(path.basename(inputs.datPath)).toBe('things_objectbuilder.dat');
    expect(path.basename(inputs.sprPath!)).toBe('things.spr');
    expect(path.basename(inputs.otmlPath!)).toBe('things.otml');
    expect(path.basename(inputs.otfiPath!)).toBe('things.otfi');
    expect(inputs.folderOrigin).toBe('--things');
  });

  it('falls back to a single *.dat/*.spr and aborts on ambiguous candidates', () => {
    const single = syntheticFolder({ 'custom.dat': dat, 'custom.spr': spr });
    const inputs = resolveThingsInputs({ things: single }, { env: {} });
    expect(path.basename(inputs.datPath)).toBe('custom.dat');
    expect(inputs.otmlPath).toBeNull();

    const ambiguous = syntheticFolder({ 'a.dat': dat, 'b.dat': dat, 'things.spr': spr });
    expect(() => resolveThingsInputs({ things: ambiguous }, { env: {} })).toThrow(
      /a\.dat, b\.dat[\s\S]*--dat/,
    );
  });

  it('applies --dat/--spr > --things > env > default precedence', () => {
    const fromEnv = syntheticFolder({ 'things.dat': dat, 'things.spr': spr });
    const fromDefault = syntheticFolder({ 'things.dat': dat, 'things.spr': spr });
    const exact = syntheticFolder({ 'exact name.dat': dat, 'exact name.spr': spr });

    const env = { PKA_DECRYPTED_THINGS: fromEnv };
    expect(resolveThingsInputs({}, { env, defaultDir: fromDefault }).folder).toBe(fromEnv);
    expect(resolveThingsInputs({}, { env: {}, defaultDir: fromDefault }).folderOrigin).toBe(
      'predeterminada',
    );
    const explicit = resolveThingsInputs(
      {
        things: fromDefault,
        dat: `"${path.join(exact, 'exact name.dat').replaceAll('\\', '/')}"`,
        spr: path.join(exact, 'exact name.spr'),
      },
      { env },
    );
    expect(explicit.datPath).toBe(path.join(exact, 'exact name.dat'));
    expect(explicit.sprPath).toBe(path.join(exact, 'exact name.spr'));
    expect(explicit.origins.dat).toBe('--dat');
  });

  it('looks for the SPR and side files next to an explicit --dat, never in another folder', () => {
    const datFolder = syntheticFolder({
      'things.dat': dat,
      'things.spr': spr,
      'things.otml': 'creatures:\n',
    });
    const envFolder = syntheticFolder({ 'things.dat': dat, 'things.spr': spr });
    const inputs = resolveThingsInputs(
      { dat: path.join(datFolder, 'things.dat') },
      { env: { PKA_DECRYPTED_THINGS: envFolder }, defaultDir: path.join(scratch, 'missing') },
    );
    expect(inputs.folder).toBeNull();
    expect(inputs.sprPath).toBe(path.join(datFolder, 'things.spr'));
    expect(inputs.otmlPath).toBe(path.join(datFolder, 'things.otml'));
    expect(inputs.origins.spr).toBe('junto al --dat');
  });

  it('treats the SPR as optional when not required (e.g. --list), even if ambiguous', () => {
    const ambiguous = syntheticFolder({ 'things.dat': dat, 'x.spr': spr, 'y.spr': spr });
    expect(() => resolveThingsInputs({ things: ambiguous }, { env: {} })).toThrow(
      /varios archivos \.spr/,
    );
    const optional = resolveThingsInputs({ things: ambiguous }, { env: {}, requireSpr: false });
    expect(optional.sprPath).toBeNull();
    const datOnly = syntheticFolder({ 'things.dat': dat });
    expect(
      resolveThingsInputs({ things: datOnly }, { env: {}, requireSpr: false }).sprPath,
    ).toBeNull();
  });

  it('applies the legacy PKA_DAT_NAME only without --things', () => {
    const folder = syntheticFolder({ 'things.dat': dat, 'legacy.dat': dat, 'things.spr': spr });
    const env = { PKA_DECRYPTED_THINGS: folder, PKA_DAT_NAME: 'legacy.dat' };
    expect(path.basename(resolveThingsInputs({}, { env }).datPath)).toBe('legacy.dat');
    expect(path.basename(resolveThingsInputs({ things: folder }, { env }).datPath)).toBe(
      'things.dat',
    );
  });

  it('reports missing folders/files and refuses PKA1 inputs', () => {
    const missing = path.join(scratch, 'does-not-exist');
    expect(() => resolveThingsInputs({ things: missing }, { env: {} })).toThrow(
      /No existe la carpeta de things/,
    );
    const noSpr = syntheticFolder({ 'things.dat': dat, 'things.spr.part1': 'x' });
    expect(() => resolveThingsInputs({ things: noSpr }, { env: {} })).toThrow(/things\.spr\.part1/);
    expect(
      resolveThingsInputs({ things: noSpr }, { env: {}, requireSpr: false }).sprPath,
    ).toBeNull();
    const encrypted = syntheticFolder({
      'things.dat': Buffer.from('PKA1\0\0\0\0'),
      'things.spr': spr,
    });
    expect(() => resolveThingsInputs({ things: encrypted }, { env: {} })).toThrow(/PKA1/);
  });

  it('refuses output inside the things folder, the client install and public/', () => {
    const folder = syntheticFolder({ 'things.dat': dat, 'things.spr': spr });
    const inputs = resolveThingsInputs({ things: folder }, { env: {} });
    const repoRoot = path.join(scratch, 'repo');
    const guard = (out: string, allowPublic = false) =>
      assertSafeOutputDir(out, { inputs, repoRoot, allowPublic, env: {} });
    expect(() => guard(path.join(folder, 'dump'))).toThrow(/carpeta de los archivos things/);
    expect(() => guard(path.join(CLIENT_INSTALL_DIR, 'dump'))).toThrow(
      /Ruta de salida no permitida/,
    );
    expect(() => guard(path.join(repoRoot, 'public', 'sprites'))).toThrow(/--registrar/);
    expect(() => guard(path.join(repoRoot, 'public', 'sprites'), true)).not.toThrow();
    expect(() => guard(path.join(scratch, 'dump-output'))).not.toThrow();
    // Folder names that merely start with ".." are still inside.
    expect(() => guard(path.join(folder, '..x'))).toThrow(/carpeta de los archivos things/);
    expect(() => guard(path.join(repoRoot, 'public', '..dump'))).toThrow(/--registrar/);
    expect(() =>
      assertSafeOutputDir(folder, {
        inputs,
        repoRoot,
        env: {},
        label: 'Archivo de mapeo no permitido',
      }),
    ).toThrow(/Archivo de mapeo no permitido/);
  });

  it('reuses only empty folders or earlier dumps of the same tool', () => {
    const ownership = { readmeFirstLine: 'Synthetic dump header', tool: 'synthetic-tool' };
    const check = (files: Record<string, string>) => () =>
      assertReusableOutputDir(syntheticFolder(files), ownership);
    expect(() =>
      assertReusableOutputDir(path.join(scratch, 'not-created'), ownership),
    ).not.toThrow();
    expect(check({})).not.toThrow();
    expect(check({ 'README.txt': 'Synthetic dump header\n===\n' })).not.toThrow();
    expect(check({ 'manifest.json': '{"tool":"synthetic-tool"}' })).not.toThrow();
    expect(check({ 'README.txt': 'my notes' })).toThrow(/README\.txt de otro origen/);
    expect(check({ 'manifest.json': '{"myApp":1}' })).toThrow(/manifest\.json de otro origen/);
    expect(check({ 'notes.txt': 'x' })).toThrow(/no está vacía/);
  });

  it('normalizes quoted Windows-style paths and compares containment safely', () => {
    const spaced = path.join(scratch, 'Some Folder', 'things');
    expect(normalizeUserPath(`"${spaced.replaceAll('\\', '/')}"`)).toBe(spaced);
    // A Windows shell turns `"C:\dir\"` into `C:\dir"`; the stray quote is dropped.
    expect(normalizeUserPath(`${spaced}${path.sep}"`)).toBe(spaced);
    expect(normalizeUserPath('things', scratch)).toBe(path.join(scratch, 'things'));
    expect(isPathInside(path.join(scratch, 'a', 'b'), scratch)).toBe(true);
    expect(isPathInside(`${scratch}-sibling`, scratch)).toBe(false);
    expect(isPathInside(path.join(scratch, '..x'), scratch)).toBe(true);
    expect(isPathInside(path.join(scratch, '..'), scratch)).toBe(false);
    expect(isPathInside(path.join(scratch, '..', 'other'), scratch)).toBe(false);
  });
});

describe('OTML and OTFI side files (synthetic text)', () => {
  it('indexes things.otml creatures and decodes values', () => {
    const tree = parseOtml(
      [
        'creatures:',
        '  7',
        '    name-displacement: -10 -16',
        '  93',
        '    opacity: 0.7',
        'items:',
        '  18832',
        '    menu',
        '      reset Reset',
      ].join('\n'),
    );
    const creatures = indexOtmlSection(tree, 'creatures');
    expect(creatures.get(7)).toEqual({ 'name-displacement': [-10, -16] });
    expect(creatures.get(93)).toEqual({ opacity: 0.7 });
    expect(indexOtmlSection(tree, 'items').get(18832)).toEqual({ menu: { reset: 'Reset' } });
  });

  it('reads the DAT/SPR format flags from things.otfi', () => {
    const { format } = parseOtfi(
      'DatSpr\n  extended: false\n  transparency: true\n  frame-durations: true\n  frame-groups: true\n',
    );
    expect(format).toEqual({
      extended: false,
      transparency: true,
      frameDurations: true,
      frameGroups: true,
    });
  });
});

describe('--list summary across frame groups (synthetic fixtures)', () => {
  it('reports mask, addons and mount found in any frame group', () => {
    const format = { extended: false, frameGroups: true, frameDurations: false };
    const outfit = syntheticThing(
      [],
      [
        { type: 0, width: 1, height: 1, px: 4, sprites: [1, 2, 3, 4] },
        {
          type: 1,
          width: 2,
          height: 2,
          layers: 2,
          px: 4,
          py: 2,
          pz: 2,
          sprites: Array.from({ length: 2 * 2 * 2 * 4 * 2 * 2 }, (_, index) => index + 1),
        },
      ],
      format,
    );
    const thing = parseDat(syntheticDat({ outfits: [outfit] }), {
      format: { ...format, transparency: true },
    }).things.outfits.get(1)!;
    const summary = summarizeOutfit(thing);
    expect(summary).toMatchObject({
      width: 1,
      layers: 1,
      patternY: 1,
      patternZ: 1,
      frameGroups: ['idle', 'moving'],
      hasMask: true,
      hasAddons: true,
      hasMount: true,
      emptySpriteIds: false,
    });
    expect(summary.groups).toHaveLength(2);
    expect(listCells(summary)).toMatchObject({
      size: '1x1 (32x32px)/2x2 (64x64px)',
      layers: '1/2',
      patternY: '1/2',
      patternZ: '1/2',
      frameGroups: 'idle+moving',
    });
  });
});

describe('dump CLI end to end (synthetic fixtures)', () => {
  const script = fileURLToPath(new URL('../../scripts/assets/dump-outfits.mjs', import.meta.url));
  // Synthetic outfit 1: 1x1 tile, 4 directions, 2 phases (sprites 1..8). Outfit 2: no sprites.
  const cliOutfit = syntheticThing(
    [],
    [{ width: 1, height: 1, px: 4, phases: 2, sprites: [1, 2, 3, 4, 5, 6, 7, 8] }],
  );
  const cliDat = syntheticDat({ outfits: [cliOutfit, emptyOutfit] });
  const cliSpr = syntheticSpr(
    Array.from({ length: 8 }, (_, index) => solidTile(40 + index * 20, 10, 200)),
  );

  function cli(args: string[], mappingFile: string, spritesDir?: string) {
    const env: Record<string, string | undefined> = { ...process.env };
    delete env.PKA_DECRYPTED_THINGS;
    delete env.PKA_DAT_NAME;
    env.PKA_OUTFIT_MAPPING = mappingFile;
    // Never let a test write the repository's public/sprites.
    env.PKA_SPRITES_DIR = spritesDir ?? path.join(scratch, `unused-sprites-${folderCounter++}`);
    return spawnSync(process.execPath, [script, ...args], { encoding: 'utf8', env });
  }

  function fixture() {
    const things = syntheticFolder({ 'things.dat': cliDat, 'things.spr': cliSpr });
    const mappingFile = path.join(syntheticFolder({}), 'outfits.json');
    writeFileSync(
      mappingFile,
      '{\n  "outfits": [\n    {\n      "pokemon": "synthetic-mon",\n      "outfitId": 1,\n      "addons": []\n    }\n  ]\n}\n',
    );
    return { things, mappingFile, out: path.join(scratch, `cli-out-${folderCounter++}`) };
  }

  it('dumps frames, sheets and records, skipping empty sheets and up-to-date outfits', () => {
    const { things, mappingFile, out } = fixture();
    const first = cli(['--things', things, '--all', '--sheet', '--out', out], mappingFile);
    expect(first.status).toBe(0);
    const record = JSON.parse(readFileSync(path.join(out, 'outfit-1', 'outfit.json'), 'utf8'));
    expect(record.mappedSlugs).toEqual(['synthetic-mon']);
    expect(record.frames).toHaveLength(8);
    expect(record.files.map((file: { file: string }) => file.file)).toContain('sheet.png');
    expect(record.client.datCounts.outfits).toBe(2);
    expect(record.client.sprSpriteCount).toBe(8);
    expect(record.source).toBeUndefined();
    expect(existsSync(path.join(out, 'outfit-1', 'default_south_a0_m0_p1.png'))).toBe(true);
    const empty = JSON.parse(readFileSync(path.join(out, 'outfit-2', 'outfit.json'), 'utf8'));
    expect(empty.sheet.image).toBeNull();
    expect(existsSync(path.join(out, 'outfit-2', 'sheet.png'))).toBe(false);
    expect(readFileSync(path.join(out, 'README.txt'), 'utf8')).toMatch(/NO están establecidos/);

    const again = cli(['--things', things, '--all', '--sheet', '--out', out], mappingFile);
    expect(again.status).toBe(0);
    expect(again.stdout).toMatch(/0 outfits escritos, 2 omitidos/);
  });

  it('validates every option before writing the --map entry', () => {
    const { things, mappingFile, out } = fixture();
    const before = readFileSync(mappingFile, 'utf8');
    const badId = cli(
      ['--things', things, '--map', 'other-mon=1', '--id', '99', '--out', out],
      mappingFile,
    );
    expect(badId.status).toBe(1);
    expect(badId.stderr).toMatch(/no existe en el DAT/);
    const badOut = cli(
      [
        '--things',
        things,
        '--map',
        'other-mon=1',
        '--slug',
        'other-mon',
        '--out',
        path.join(things, 'dump'),
      ],
      mappingFile,
    );
    expect(badOut.status).toBe(1);
    expect(readFileSync(mappingFile, 'utf8')).toBe(before);
    expect(existsSync(out)).toBe(false);

    const ok = cli(
      ['--things', things, '--map', 'other-mon=1', '--slug', 'other-mon', '--out', out],
      mappingFile,
    );
    expect(ok.status).toBe(0);
    expect(JSON.parse(readFileSync(mappingFile, 'utf8'))).toEqual({
      outfits: [
        { pokemon: 'synthetic-mon', outfitId: 1, addons: [] },
        { pokemon: 'other-mon', outfitId: 1, addons: [] },
      ],
    });
  });

  it('registers the idle frames of the dumped outfits in the sprite folder', () => {
    const { things, mappingFile, out } = fixture();
    const spritesDir = path.join(scratch, `sprites-${folderCounter++}`);
    const dry = cli(
      ['--things', things, '--id', '1', '--registrar', '--dry-run', '--out', out],
      mappingFile,
      spritesDir,
    );
    expect(dry.status).toBe(0);
    expect(existsSync(spritesDir)).toBe(false);

    const empty = cli(
      ['--things', things, '--id', '2', '--registrar', '--out', out],
      mappingFile,
      spritesDir,
    );
    expect(empty.status).toBe(1);
    expect(empty.stderr).toMatch(/--registrar 2: está vacío/);
    expect(existsSync(out)).toBe(false);

    const result = cli(
      ['--things', things, '--slug', 'synthetic-mon', '--registrar', '--out', out],
      mappingFile,
      spritesDir,
    );
    expect(result.status).toBe(0);
    expect(result.stdout).toMatch(/outfits\/1 · 32×32 · norte, este, sur, oeste · nuevo/);
    for (const [english, spanish] of [
      ['north', 'norte'],
      ['east', 'este'],
      ['south', 'sur'],
      ['west', 'oeste'],
    ]) {
      expect(readFileSync(path.join(spritesDir, 'outfits', '1', `${spanish}.png`))).toEqual(
        readFileSync(path.join(out, 'outfit-1', `default_${english}_a0_m0_p0.png`)),
      );
    }
    const registry = JSON.parse(readFileSync(path.join(spritesDir, 'sprites.json'), 'utf8'));
    expect(registry.sprites['outfits/1']).toEqual({
      archivo: 'outfits/1/sur.png',
      frame: [32, 32],
      frames: 1,
      modo: 'estatico',
      direcciones: {
        norte: 'outfits/1/norte.png',
        este: 'outfits/1/este.png',
        sur: 'outfits/1/sur.png',
        oeste: 'outfits/1/oeste.png',
      },
    });

    const again = cli(
      ['--things', things, '--id', '1', '--registrar', '--out', out],
      mappingFile,
      spritesDir,
    );
    expect(again.status).toBe(0);
    expect(again.stdout).toMatch(/outfits\/1 · 32×32 · norte, este, sur, oeste · sin cambios/);
  });

  it('lists from a DAT-only folder without recording input paths or hashes', () => {
    const datOnly = syntheticFolder({ 'things.dat': cliDat });
    const { mappingFile } = fixture();
    const result = cli(['--things', datOnly, '--list', '--json'], mappingFile);
    expect(result.status).toBe(0);
    const listing = JSON.parse(result.stdout);
    expect(listing.client.datCounts.outfits).toBe(2);
    expect(listing.client.sprSpriteCount).toBeNull();
    expect(listing.source).toBeUndefined();
    expect(listing.outfits.map((row: { id: number }) => row.id)).toEqual([1, 2]);
    expect(listing.outfits[1].emptySpriteIds).toBe(true);
  });

  it('refuses guarded, foreign or empty output paths and PKA1 inputs', () => {
    const { things, mappingFile } = fixture();
    const inside = cli(
      ['--things', things, '--id', '1', '--out', path.join(things, '..x')],
      mappingFile,
    );
    expect(inside.status).toBe(1);
    expect(existsSync(path.join(things, '..x'))).toBe(false);

    const foreign = syntheticFolder({ 'README.txt': 'my own notes' });
    const reused = cli(['--things', things, '--id', '1', '--out', foreign], mappingFile);
    expect(reused.status).toBe(1);
    expect(readFileSync(path.join(foreign, 'README.txt'), 'utf8')).toBe('my own notes');

    expect(cli(['--things', things, '--id', '1', '--out', ''], mappingFile).status).toBe(1);

    const encrypted = syntheticFolder({
      'things.dat': Buffer.from('PKA1\0\0\0\0'),
      'things.spr': cliSpr,
    });
    const refused = cli(['--things', encrypted, '--list'], mappingFile);
    expect(refused.status).toBe(1);
    expect(refused.stderr).toMatch(/PKA1/);
  });
});
