// §14.3 SEO gate over the Vercel output: the parts of §13.5 and §8 that a file on
// disk cannot show, because they live in `.vercel/output/config.json` or in an
// on-demand function. The redirections of §8.0.1 (RZ1, RZ2, RZ3, MP2), the 404 of
// each locale (NF1) and, over a sample of routes, `robots.txt` and the sitemap.
// Everything that a built page carries on its own — title, description, canonical,
// hreflang, Open Graph, duplicate titles — is `seo:check`
// (scripts/seo/check-dist.mjs), which reads the same output without a browser.
//
// Runs in the `prod` project: the emulator of §14.3 walks `routes` of the real
// `config.json`, so a redirection tested here is the one that gets deployed and
// not a copy of the table in `astro.config.mjs`.
//
// Contract with tests/e2e/routes.ts (track C of M2): `outputRoutes` is the §14.4
// list trimmed by scripts/lib/rutas-migradas.mjs and by the `/_paridad/` routes,
// which only the development server serves (§14.5), and each entry carries `path`,
// `locale` and `status` (200, or 404 for the two adds of §14.4).
//
// Scope: RZ2 on `/{l}/` and RZ1 on `/` (§8.13); MP2 on `/{l}/mapa/` and the other two 302
// of §8.0.1; NF1 on the two 404 of §14.4; robots.txt and the sitemap on the sample itself.

import { expect, test, type APIRequestContext } from '@playwright/test';
import { idiomas } from '../../scripts/lib/rutas-migradas.mjs';
import { outputRoutes } from './routes';

/** §13.5: `site` of astro.config.mjs, the origin every absolute URL of the output uses. */
const SITE = 'https://pokealliance-codex.vercel.app';

/** §13.5: the sitemap `robots.txt` points at, generated by `@astrojs/sitemap`. */
const SITEMAP = '/sitemap-index.xml';

/** §8.13: the root answers a redirection declared in configuration, never a page. */
const ROOT = '/';
const ROOT_TARGET = '/es/';

/** §8.0.1: the three 302, with the route whose milestone brings each one. */
const REDIRECTS = [
  // A1, MP2: «Aportar al mapa» goes away with the map placeholder of §8.11.
  { from: '/{l}/mapa/aportar/', to: '/{l}/mapa/' },
  // R15: the tiers move into the Tier list of §8.8.
  { from: '/{l}/rotaciones/', to: '/{l}/pokedex/tiers/' },
  // A7: the quests live in Actividades (§8.9).
  { from: '/{l}/guias/', to: '/{l}/actividades/' },
];

/** §8.12, NF1: an unknown locale answers the 404 in `es`. */
const UNKNOWN_LOCALE = ['/xx/', '/xx/pokedex/'];

/** §8.12: the h1 of the 404 page in each locale. */
const NOT_FOUND_TITLE = { es: 'Página no encontrada', en: 'Page not found' };

/** §8.0.1: the redirections of the site are temporary, so 302 and nothing else. */
const REDIRECT_STATUS = 302;

function isRedirect(status: number): boolean {
  return status >= 300 && status < 400;
}

function forLocale(template: string, locale: string): string {
  return template.replaceAll('{l}', locale);
}

/** §8.0.1: «aceptan la ruta con y sin barra final». */
function withoutSlash(path: string): string {
  return path.length > 1 && path.endsWith('/') ? path.slice(0, -1) : path;
}

/** §13.5: the `robots` tag of a page, or `null` when it carries none. */
function robotsTag(html: string): string | null {
  const tag = /<meta\s[^>]*name=["']robots["'][^>]*>/i.exec(html);
  if (tag === null) return null;
  return /content=["']([^"']*)["']/i.exec(tag[0])?.[1] ?? '';
}

/**
 * Every `<loc>` of the sitemap index and of the sitemaps it lists. Read once per
 * worker: the sample visits it one route at a time and the file does not change
 * during a run.
 */
let sitemapUrls: Promise<string[]> | null = null;

async function locations(request: APIRequestContext, path: string): Promise<string[]> {
  const response = await request.get(path);
  expect(response.status(), `${path} answers`).toBe(200);
  const body = await response.text();
  return [...body.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)].map((match) => match[1]);
}

async function readSitemap(request: APIRequestContext): Promise<string[]> {
  sitemapUrls ??= (async () => {
    const indexed = await locations(request, SITEMAP);
    const urls: string[] = [];
    for (const child of indexed) urls.push(...(await locations(request, new URL(child).pathname)));
    return urls;
  })();
  return sitemapUrls;
}

// The root is not a route of scripts/lib/rutas-migradas.mjs and never will be: since M11 it
// is a 302 of astro.config.mjs with no HTML behind it (§8.13, T16), so RZ1 always runs.
test.describe('§8.13: the root and the locale roots', () => {
  test('RZ1: / answers 302 to /es/ with no meta refresh', async ({ request }) => {
    const response = await request.get(ROOT, { maxRedirects: 0 });

    expect(response.status(), 'RZ1: the root redirects').toBe(REDIRECT_STATUS);
    expect(response.headers()['location'], 'RZ1: towards the Spanish home').toBe(ROOT_TARGET);
    expect(await response.text(), 'RZ1: no HTML body with http-equiv="refresh"').not.toContain(
      'http-equiv',
    );
  });
});

for (const locale of idiomas) {
  const home = `/${locale}/`;

  test.describe(`§8.13: ${home} without its trailing slash`, () => {
    test(`RZ2: /${locale} ends in the ${locale} home after one redirection at most`, async ({
      request,
    }) => {
      const first = await request.get(`/${locale}`, { maxRedirects: 0 });
      expect(
        isRedirect(first.status()) || first.status() === 200,
        `RZ2: /${locale} answers or redirects, it does not fail with ${first.status()}`,
      ).toBe(true);

      // §3.13 fixes the trailing-slash policy, not the status code of that one hop, so
      // any 3xx counts here; the three redirections of §8.0.1 are the ones pinned to 302.
      const final = isRedirect(first.status())
        ? await request.get(first.headers()['location'] ?? '', { maxRedirects: 0 })
        : first;

      expect(final.status(), 'RZ2: it ends in 200').toBe(200);
      expect(await final.text(), 'RZ2: it is the home of that locale').toContain(
        `lang="${locale}"`,
      );
    });
  });
}

for (const redirect of REDIRECTS) {
  for (const locale of idiomas) {
    const from = forLocale(redirect.from, locale);
    const to = forLocale(redirect.to, locale);

    test.describe(`§8.0.1: ${from} redirects`, () => {
      test(`${from} and ${withoutSlash(from)} answer 302 to ${to}`, async ({ request }) => {
        for (const path of [from, withoutSlash(from)]) {
          const response = await request.get(path, { maxRedirects: 0 });
          expect(response.status(), `${path} redirects`).toBe(REDIRECT_STATUS);
          expect(response.headers()['location'], `${path} lands on ${to}`).toBe(to);
        }

        // RZ3: the target is the end of the chain, not another redirection.
        expect((await request.get(to, { maxRedirects: 0 })).status(), `${to} answers 200`).toBe(
          200,
        );
      });
    });
  }
}

for (const route of outputRoutes) {
  test(`RZ3: ${route.path} answers without a redirection chain`, async ({ request }) => {
    const canonical = await request.get(route.path, { maxRedirects: 0 });
    expect(canonical.status(), 'the canonical route answers straight away').toBe(route.status);

    const bare = withoutSlash(route.path);
    if (bare === route.path) return;

    const first = await request.get(bare, { maxRedirects: 0 });
    if (first.status() === route.status) return;

    expect(isRedirect(first.status()), `${bare} either answers or redirects once`).toBe(true);
    const second = await request.get(first.headers()['location'] ?? '', { maxRedirects: 0 });
    expect(second.status(), 'RZ3: no second redirection').toBe(route.status);
  });
}

for (const route of outputRoutes.filter((candidate) => candidate.status === 404)) {
  test(`NF1: ${route.path} answers the ${route.locale} 404, noindex`, async ({ request }) => {
    const response = await request.get(route.path, { maxRedirects: 0 });
    expect(response.status(), 'NF1: status 404').toBe(404);

    const html = await response.text();
    expect(html, `NF1: the page of ${route.locale}`).toContain(`lang="${route.locale}"`);
    expect(html, 'NF1: the h1 of that locale').toContain(NOT_FOUND_TITLE[route.locale]);
    expect(robotsTag(html), '§13.5: the 404 is noindex').toContain('noindex');
  });

  if (route.locale === 'es') {
    test('NF1: an unknown locale answers the 404 in es', async ({ request }) => {
      for (const path of UNKNOWN_LOCALE) {
        const response = await request.get(path, { maxRedirects: 0 });
        expect(response.status(), `${path} answers 404`).toBe(404);
        expect(await response.text(), `${path} falls back to es`).toContain('lang="es"');
      }
    });
  }
}

test.describe('§13.5: crawling', () => {
  // No sample here: `public/robots.txt` and `@astrojs/sitemap` are site-wide and arrive
  // with the frame (M3), not with a route, so this one is measured from the milestone
  // that adds them, whatever `outputRoutes` holds. The route-by-route agreement between
  // the sitemap and the robots tag below is the one that waits for a migrated page.
  test('robots.txt allows everything and points at the sitemap', async ({ request }) => {
    const response = await request.get('/robots.txt');
    expect(response.status(), 'robots.txt is in the output').toBe(200);

    const body = await response.text();
    expect(body, '§13.5: User-agent: *').toContain('User-agent: *');
    expect(body, '§13.5: Allow: /').toContain('Allow: /');
    expect(body, '§13.5: the absolute URL of the sitemap').toContain(`Sitemap: ${SITE}${SITEMAP}`);
  });
});

for (const route of outputRoutes) {
  test(`§13.5: the sitemap agrees with the robots tag of ${route.path}`, async ({ request }) => {
    const response = await request.get(route.path, { maxRedirects: 0 });
    const noindex = (robotsTag(await response.text()) ?? '').includes('noindex');
    const urls = await readSitemap(request);
    const url = `${SITE}${route.path}`;

    if (noindex) expect(urls, '§13.5: a noindex route is not in the sitemap').not.toContain(url);
    else expect(urls, '§13.5: an indexable route is in the sitemap').toContain(url);
  });
}
